Clients/urls.py
# monapp/urls.py
from django.urls import path
from . import views  

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('login-view/', views.login_view, name='login_view'),
    path('account_view/', views.account_views, name='account_views'),
    path('logout/', views.logout_view, name='logout'),
    path('postuler/', views.postuler, name='postuler'),
    path('confirmation/', views.confirmation, name='confirmation'),
    # ... d'autres URL de votre application ...
]

panier/urls.py
# cart/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import add_to_cart, clear_cart, view_cart, supprimer_panier

urlpatterns = [
    # ... d'autres URLs ...
      path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
      path('supprimer_panier/<int:product_id>/', supprimer_panier, name='supprimer_panier'),
      path('view_cart', view_cart, name='view_cart'),
      path('clear-cart/', clear_cart, name='clear_cart'),
      path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
       
      
]

produits/urls.py
from django.urls import path
from . import views
urlpatterns= [
    path('', views.home, name= 'home'), 
    path('a_propos', views.a_propos, name='a_propos'),
    # URL pour la vue de détail du produit
    path('ajouter_produit/<int:product_id>/', views.ajouter_produit, name='ajouter_produit'),
    path('editer_produit/<int:product_id>/', views.editer_produit, name='editer_produit'),
    path('produits/<int:product_id>/', views.supprimer_produit, name='supprimer_produit'),
    #path('produits/update_cart/<int:product_id>/', views.update_cart, name='update_cart'),
    # Ajoutez l'URL pour la recherche de produits
    path('produits/', views.rechercher_produits, name='rechercher_produits')   
]

projet/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('produits/', include('produits.urls')),
    path('Clients/', include('Clients.urls')),
    path('panier/', include(('panier.urls'))),
     path('commande/', include(('commande.urls'))),
]
# Ajoutez cette ligne pour activer les messages


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Clients/models.py
from django import forms
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

class CustomerUser(AbstractUser):
        email= models.EmailField(unique=True)
        prenom= models.CharField(max_length=30, blank=True)
        nom= models.CharField(max_length=30, blank=True) 
        numero_telephone = models.CharField(max_length=9, blank=True)
        date_joined= models.DateTimeField(default=timezone.now)

        def __str__(self):
            return self.email
class Cart(models.Model):
    user = models.OneToOneField(CustomerUser, on_delete=models.CASCADE)
    # ... autres champs de votre panier ...

@receiver(post_save, sender=CustomerUser)
def create_or_update_cart(sender, instance, created, **kwargs):
    if created:
        # L'utilisateur vient d'être créé, donc nous créons un panier pour lui
        Cart.objects.create(user=instance)
    else:
        # L'utilisateur existe déjà, nous mettons à jour le panier s'il existe
        if hasattr(instance, 'cart'):
            cart = instance.cart
            # Mettre à jour les champs du panier si nécessaire
            cart.save()
        else:
            # L'utilisateur n'a pas de panier, donc nous le créons
            Cart.objects.create(user=instance)


class Postulation(models.Model):
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    email = models.EmailField()
    cv = models.FileField(upload_to='cv/')

    def __str__(self):
        return f"{self.nom} {self.prenom}"

produits/models.py
from typing import Any
from django.db import models

# Create your models here.
class Categorie(models.Model):
   name= models.CharField(max_length=200, null=True)
   def __str__(self):
       return self.name
class Product(models.Model):
    image= models.ImageField(upload_to='images/')
    title= models.CharField(max_length=150,null=True)
    price= models.FloatField(default=0.0)
    quantity=models.PositiveIntegerField(default=0)
    description=models.CharField(max_length=300,null=True)
    category=models.ForeignKey(Categorie, on_delete=models.CASCADE)
    def __str__(self):
        return self.title
class  Collection(models.Model):
    img= models.ImageField(upload_to='images/')
    titre= models.CharField(max_length=200, null=True)
    descriptions= models.CharField(max_length=200,null=True)
    prix= models.FloatField(default=0.0)
    categorie= models.ForeignKey(Categorie, on_delete=models.CASCADE)
    def __str__(self) :
        return self.titre
    

Clients/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomerUser
from django.utils import timezone

from django import forms
from .models import Postulation

class CustomUserCreationForm(UserCreationForm):
    date_joined = forms.CharField(label='Date joined', required=False)
    class Meta:
        model = CustomerUser
        fields = ['email', 'prenom', 'nom', 'numero_telephone','password1', 'password2','date_joined']

    widgets = {
        'username': forms.TextInput(),
        'email': forms.EmailInput(),
    }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Formatage de la date de création pour l'affichage dans le formulaire
        self.fields['date_joined'].initial = timezone.now().strftime("%Y-%m-%d %H:%M:%S")
        self.fields['date_joined'].widget.attrs['readonly'] = True

class LoginForm(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(widget=forms.PasswordInput, label='Password')

class PostulationForm(forms.ModelForm):
    class Meta:
        model = Postulation
        fields = ['nom', 'prenom', 'email', 'cv']

produits/forms.py
from django import forms
from .models import Product,Categorie, Collection

class ProduitForm(forms.ModelForm):
    class Meta:
        model = Product
        fields= [ 'category', 'title', 'price', 'description', 'quantity']


class CollectionForm(forms.ModelForm):
    class Meta:
        model = Collection
        fields= [ 'img', 'descriptions', 'categorie', 'prix']


# forms.py
from django import forms

class RechercheProduitForm(forms.Form):
    q = forms.CharField(max_length=100, required=False, label='Terme de recherche')
    category = forms.ModelChoiceField(queryset=Categorie.objects.all(), empty_label="Toutes les catégories", required=False)
    def clean_q(self):
        q = self.cleaned_data.get('q', '').strip()
        if not q:
            raise forms.ValidationError("Le champ de recherche ne peut pas être vide.")
        self.query = q 
        return q

Clients/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from .forms import CustomUserCreationForm, LoginForm
from .forms import PostulationForm
from django.contrib import messages

#////// ¨Posstulation


def postuler(request):
    if request.method == 'POST':
        form = PostulationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('confirmation')
    else:
        form = PostulationForm()
    return render(request, 'clients/postulation.html', {'form': form})

def confirmation(request):
    # Ajoutez des données spécifiques à afficher dans le modèle de confirmation
    confirmation_message = "Votre candidature a été soumise avec succès."
    return render(request, 'clients/confirmation.html', {'confirmation_message': confirmation_message})


@login_required
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            messages.success(request, 'Inscription réussie. Vous êtes maintenant connecté.')
            return redirect('profile')  # Redirigez l'utilisateur après l'inscription
    else:
        form = CustomUserCreationForm()
         
    return render(request, 'clients/signup.html', {'form': form})

@login_required
def profile(request):
    return render(request, 'clients/profile.html', {'user': request.user})

@login_required
def account_views(request):
    return render(request, 'clients/account.html', {'user': request.user})

@login_required
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['email']  # Assurez-vous que 'email' est le nom du champ email dans le formulaire LoginForm
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('profile')  # Redirigez vers la page du profil après la connexion
            else:
                messages.error(request, 'Nom d\'utilisateur ou mot de passe incorrect')
    else:
        form = LoginForm()

    return render(request, 'clients/login.html', {'form': form})

@login_required
def logout_view(request):
    logout(request)
    return redirect('login_view')

produits/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Categorie, Collection
from .forms import ProduitForm
from panier.models import CartItem
from django.contrib.auth.decorators import login_required
from panier.views import view_cart
from django.db.models import Sum 
# Create your views here.
def home(request):
    produits= Product.objects.all()
    categories = Categorie.objects.all()
    product= Collection.objects.all()
        # Calculer la quantité totale du panier
    total_quantity = 0
    if request.user.is_authenticated:
        total_quantity = CartItem.objects.filter(user=request.user).aggregate(total_quantity=Sum('quantity'))['total_quantity'] or 0

    # Ajouter la quantité totale du panier au contexte
    context = {'produits': produits, 'categories': categories, 'product':product,
               'total_quantity': total_quantity}
    
    return render(request,'produits/listproduit.html', context)

# vifrom django.shortcuts import render, redirect
def a_propos(request):
        # Calculer la quantité totale du panier
    total_quantity = 0
    if request.user.is_authenticated:
        total_quantity = CartItem.objects.filter(user=request.user).aggregate(total_quantity=Sum('quantity'))['total_quantity'] or 0

    # Ajouter la quantité totale du panier au contexte
    context = { 'total_quantity': total_quantity}
    return render(request, 'base/Apropos.html', context)

def ajouter_produit(request, product_id):
    # Récupérez le produit à afficher (par exemple, le produit avec l'ID 1)
    
    produit = Product.objects.get(pk=product_id)  # Remplacez 1 par l'ID du produit que vous souhaitez afficher
    if request.method == 'POST':
        produit.add()
        return redirect('home')
    return render(request, 'produits/product_add.html', {'produit': produit })

def editer_produit(request, product_id):
    produit= get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form =ProduitForm(request.POST, instance=produit)
        if form.is_valid():
            form.save() 
            return redirect('ajouter_produit')
    else: 
        form= ProduitForm(instance=produit)
        return render(request, 'produits/product_edit.html', {'form': form, 'produit':produit})
    

@login_required
def supprimer_produit(request, product_id):
    produit = get_object_or_404(Product, pk=product_id)
    total_quantity = 0
    if request.method == 'POST':
        produit.delete()
        return redirect('home')
    if request.user.is_authenticated:
        total_quantity = CartItem.objects.filter(user=request.user).aggregate(total_quantity=Sum('quantity'))['total_quantity'] or 0
        cart_items = CartItem.objects.filter(user=request.user)  # Récupérer les éléments de panier pour l'utilisateur actuel

    context = {
        'total_quantity': total_quantity,
        'produit': produit, 
        'cart_items': cart_items
    }
    return render(request, 'produits/product_delete.html', context)

from .forms import RechercheProduitForm
from .models import Product  # Assurez-vous que vous importez correctement votre modèle Product


def rechercher_produits(request):
    if request.method == 'GET':
        form = RechercheProduitForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['q']
            produits = Product.objects.filter(title__icontains=query)
            total_quantity = 0
            if request.user.is_authenticated:
                total_quantity = CartItem.objects.filter(user=request.user).aggregate(total_quantity=Sum('quantity'))['total_quantity'] or 0

            context = {
                'query': query,
                'total_quantity': total_quantity,
                'produits': produits,
            }
            return render(request, 'produits/afficher_search.html', context)
        else:
            # Le formulaire n'est pas valide, donc nous retournons une page vide
            return render(request, 'produits/afficher_search.html', {})
    else:
        form = RechercheProduitForm()
        return render(request, 'product_search.html', {'form': form})


def commander_produit(request):
   return render(request, 'commandes/listcommande.html')

produits/templates/clients/account.html
{% extends "main.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <!-- Colonne gauche (informations du profil) -->
            <div class="card">
                
                <div class="card-body">
                    <h5 class="card-title"> <span class="icon-contact"></span>{{ user.prenom }} {{user.nom}} </h5>
                    <p class="card-text">{{ profile.phone_number }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <!-- Colonne droite (autres détails du profil) -->
            <h2>Informations du profil</h2>
            {% if is_authentificated %}
            <ul>
                <li>Nom complet : {{ user.nom}}</li>
                <li>Email : {{ user.email }}</li>
                <!-- Ajoutez d'autres détails du profil ici -->
            </ul>
            <a href="" class="btn btn-primary">compte</a>
            {% else %}
            <p>Vous ne disposer pas de compte</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

produits/templates/clients/confirmation.html
<!-- confirmation.html -->
{% extends 'main.html' %}

{% block content %}
<div class="confirmation-frame">
    <div class="confirmation-content">
        <i class="fas fa-thumbs-up like-icon"></i>
        <h1>Merci pour votre candidature !</h1>
        <p class="confirmation-message">Nous avons bien reçu votre CV.</p>
    </div>
</div>
<style type="text/css">

    body {
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
    }
    
    .confirmation-frame {
        width: 80%;
        max-width: 500px;
        margin: 50px auto;
        background-color: #fff;
        border: 1px solid #ccc;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
        text-align: center;
    }
    
    .confirmation-content {
        position: relative;
    }
    
    .like-icon {
        color: #4CAF50;
        font-size: 60px;
    }
    
    h1 {
        font-size: 24px;
        margin-top: 10px;
        margin-bottom: 10px;
    }
    
    .confirmation-message {
        font-size: 16px;
        color: #666;
        margin-top: 20px;
        margin-bottom: 0;
    }
    
</style>

{% endblock %}

produits/templates/clients/login.html
{% extends 'main.html' %}

{% block content %}

<form method="post">
  {% csrf_token %}
  <section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card bg-light text-dark" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
  
              <div class="mb-md-5 mt-md-4 pb-5">
  
                <h2 style ='font-family:Edwardian Script ITC; font-size: 76px; color: rgb(101, 67, 33); ' >Login</h2>
                <p class="text-dark mb-5">Please enter your login and password!</p>
  
                <div class="form-outline form-white mb-4">
                  {% if messages %}
                  <ul class="messages">
                      {% for message in messages %}
                          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                      {% endfor %}
                  </ul>
              {% endif %}
              
              <form method="post" action="{% url 'login_view' %}">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit">Se connecter</button>
              </form>
                <div class="d-flex justify-content-center text-center mt-4 pt-1">
                  <a href="#!" class="text-dark"><i class="fab fa-facebook-f fa-lg"></i></a>
                  <a href="#!" class="text-dark"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                  <a href="#!" class="text-dark"><i class="fab fa-google fa-lg"></i></a>
                </div>
              </div>
              <div>
                <p class="mb-0">Don't have an account? <a href="{% url 'signup' %}" class="text-dark fw-bold">Sign Up</a>
                </p>
              </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</form> 
<br><br><br>
{% endblock %}

produits/templates/clients/postulation.html
{% extends 'main.html' %}

{% block content%}
   
<div class="container">
    <h1>Formulaire de candidature</h1>
    <form method="POST" enctype="multipart/form-data" action="{% url 'postuler' %}">
        {% csrf_token %}
        <label for="id_nom">Nom:</label>
        <input type="text" id="id_nom" name="nom">

        <label for="id_prenom">Prénom:</label>
        <input type="text" id="id_prenom" name="prenom">

        <label for="id_email">Email:</label>
        <input type="email" id="id_email" name="email">

        <label for="id_telephone">Téléphone:</label>
        <input type="text" id="id_telephone" name="telephone">

        <label for="id_cv">CV:</label>
        <input type="file" id="id_cv" name="cv">

        <button type="submit">Postuler</button>
    </form>
</div>
<br>
    <style>
        /* Styles spécifiques au formulaire pour éviter l'impact du pied de page */
        .form-container {
            margin-top: 50px;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        /* Styles du formulaire */
        form {
            padding: 20px;
        }

        label {
            display: block;
            font-weight: bold;
            margin-bottom: 10px;
            color: #333;
        }

        input[type="text"],
        input[type="email"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-bottom: 20px;
        }

        input[type="file"] {
            margin-top: 10px;
        }

        /* Réinitialisation du style du pied de page */
        footer {
            /* Ajoutez vos styles pour le pied de page ici */
        }
    </style>



{% endblock %}

produits/templates/clients/profile.html
{% extends 'main.html' %}

{% block content %}
<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-md-3">
            <!-- Sidebar -->
            <div class="bg-light border-right" id="sidebar-wrapper">
                <div class="sidebar-heading">Bonjour {{ user.username }}</div>
                <div class="list-group list-group-flush">
                    <a href="#" class="list-group-item list-group-item-action bg-light">Accueil</a>
                    <a href="{% url 'commande_view'%}" class="list-group-item list-group-item-action bg-light">Commandes</a>
                    <a href="#" class="list-group-item list-group-item-action bg-light">Profil</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="list-group-item list-group-item-action bg-light">Déconnexion</a>
                    {% endif %}
                </div>
            </div>
            <!-- /#sidebar-wrapper -->
        </div>
        <div class="col-md-9">
            <!-- Page Content -->
            <div id="page-content-wrapper">
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <button class="btn btn-primary" id="menu-toggle">Menu</button>
                </nav>
                <div class="container-fluid">
                    <h1 class="mt-4">Bienvenue dans votre Menu </h1>
                    <p>Merci de notre confiance </p>
                    <!-- Bouton avec animation et couleur au survol -->
                   
                </div>
            </div>
            <!-- /#page-content-wrapper -->
        </div>
    </div>
</div>
<section>
    <h2>Welcome, User!</h2>
    <p>This is your user dashboard. You can view and manage your information here.</p>
</section>
<section>
    <h2>Recent Activity</h2>
    <ul>
        <li>Activity 1</li>
        <li>Activity 2</li>
        <li>Activity 3</li>
    </ul>
</section>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>

<style type="text/css">
    /* styles.css */
    body {
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
        margin: 0;
        padding: 0;
    }
    
    header {
        background-color: #333;
        color: #fff;
        padding: 20px;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    
    nav {
        background-color: #666;
        color: #fff;
        padding: 10px;
    }
    
    nav ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }
    
    nav ul li {
        display: inline;
        margin-right: 10px;
    }
    
    nav ul li a {
        color: #fff;
        text-decoration: none;
    }
    
    main {
        padding: 20px;
    }
    
    section {
        margin-bottom: 20px;
    }
    
    footer {
        background-color: #333;
        color: #fff;
        padding: 10px;
        text-align: center;
    }</style>
{% endblock %}

produits/templates/clients/signup.html
{% extends 'main.html' %}

{% block content %}
<section class="h-100 gradient-form">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-6">
                <div class="card rounded-3 shadow-lg p-4">
                    <h2 class="text-center mb-4" style='font-family:Edwardian Script ITC; font-size: 76px;'>Inscription</h2>
                   
                    <form method="post" action="{% url 'signup' %}" class="form-signup">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_email">Email:</label>
                            {{ form.email }}
                        </div>
                        <div class="form-group">
                            <label for="id_prenom">Prenom:</label>
                            {{ form.prenom }}
                        </div>
                        <div class="form-group">
                            <label for="id_nom">Nom:</label>
                            {{ form.nom }}
                        </div>
                        <div class="form-group">
                            <label for="id_phone_number">Numero telephone:</label>
                            {{ form.phone_number }}
                        </div>
                        <div class="form-group">
                            <label for="id_password1">Password:</label>
                            {{ form.password1 }}
                        </div>
                        <div class="form-group">
                            <label for="id_password2">Password confirmation:</label>
                            {{ form.password2 }}
                        </div>
                        <div class="form-group">
                            <label for="id_date_joined">Date joined:</label>
                            <input type="text" id="id_date_joined" value="{{ form.date_joined.value }}" readonly>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">S'inscrire</button>
                        
                        <a  class='btn btn-warning' href=" {% url 'login_view' %} "> se connecter</a> 
                    </form>   
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    // Obtenir la date actuelle
    var currentDate = new Date();
    // Formatage de la date au format désiré (ex: YYYY-MM-DD HH:MM:SS)
    var formattedDate = currentDate.toISOString().slice(0, 19).replace('T', ' ');
    // Mettre la date formatée dans le champ de date du formulaire
    document.getElementById("id_date_joined").value = formattedDate;
</script>
<style type="text/css">

    .form-signup {
        max-width: 400px;
        margin: 0 auto;
    }
    
    .form-group {
        margin-bottom: 20px;
    }
    
    label {
        display: block;
        font-weight: bold;
    }
    
    input[type="text"],
    input[type="email"],
    input[type="tel"],
    input[type="password"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
    

    
</style>


{% endblock %}